# Just the essentials - fix the actual problems we had
repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.0
    hooks:
      - id: ruff
        args: [--fix]  # Auto-fix whitespace issues