name: PR Checks

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  check-files:
    name: Check file requirements
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
    - uses: actions/checkout@v5

    - name: Check for large files
      run: |
        # Check for files larger than 1MB
        find . -type f -size +1M | grep -v "^./.git" | while read file; do
          echo "Error: File $file is larger than 1MB"
          exit 1
        done

    - name: Check for generated files
      run: |
        # Ensure no wheel files are committed
        if find . -name "*.whl" -o -name "*.egg-info" | grep -v "^./.git"; then
          echo "Error: Generated files (wheels, egg-info) should not be committed"
          exit 1
        fi

  # Coverage enforcement removed - we'll track it but not block PRs
  # Can be re-enabled once we have better test coverage for new features
